name: Docker Image CI Automation
on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: includes blueprint, run ID, and entity identifier from Port.
      agent_version:
        description: Agent version
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update progress
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        runId: ${{ fromJson(inputs.port_context).run_id }}
        logMessage: |
          Build process begins

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg AGENT_VERSION=${{ inputs.agent_version }} --tag fok666/azuredevops:$(date +%s) --tag fok666/azuredevops:latest

    - name: Update progress
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        runId: ${{ fromJson(inputs.port_context).run_id }}
        logMessage: |
          Build process ended

  push_to_registry:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Update progress
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_id }}
          logMessage: |
            Post-build actions started.

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: fok666/azuredevops

      - name: Get the date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: fok666/azuredevops:${{ steps.extract_branch.outputs.branch }}-${{ inputs.agent_version }}-${{ steps.date.outputs.date }}, fok666/azuredevops:${{ steps.extract_branch.outputs.branch }}-${{ inputs.agent_version }}-latest, fok666/azuredevops:${{ inputs.agent_version }}-latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update progress
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).run_id }}
          logMessage: |
            Workflow completed.
